"use client";

export default function SubmitSection({ locale }: { locale: string }) {
  return (
    <section id="submit" className="py-24 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto text-center">
        <div className="glass rounded-3xl p-10 sm:p-16 relative overflow-hidden">
          {/* Background glow */}
          <div className="absolute top-0 left-1/2 -translate-x-1/2 w-96 h-96 bg-neon-500/5 rounded-full blur-[128px]" />

          <div className="relative z-10">
            <div className="w-16 h-16 rounded-2xl bg-neon-500/10 flex items-center justify-center mx-auto mb-6">
              <svg
                className="w-8 h-8 text-neon-400"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={1.5}
                  d="M12 9v6m3-3H9m12 0a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
            </div>

            <h2 className="text-2xl sm:text-3xl font-bold mb-4">
              {locale === "zh"
                ? "提交你的 AI 游戏"
                : "Submit Your AI Game"}
            </h2>
            <p className="text-dark-400 mb-8 leading-relaxed">
              {locale === "zh"
                ? "你有一个完全由 AI 生成的游戏想展示？告诉我们你的 prompt 和游戏链接，我们会审核并收录到平台上。"
                : "Have a game that was entirely generated by AI? Share your prompt and game link. We'll review and feature it on the platform."}
            </p>

            <div className="flex flex-col sm:flex-row gap-3 justify-center">
              <input
                type="email"
                placeholder={locale === "zh" ? "你的邮箱" : "Your email"}
                className="px-4 py-3 rounded-xl bg-dark-800 border border-dark-600 text-white placeholder-dark-500 focus:outline-none focus:border-neon-500/50 transition-colors flex-1 max-w-md"
              />
              <button className="px-6 py-3 rounded-xl bg-gradient-to-r from-neon-500 to-neon-600 text-dark-950 font-bold hover:shadow-lg hover:shadow-neon-500/25 transition-all">
                {locale === "zh" ? "提交游戏" : "Submit Game"}
              </button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
