import { games } from "@/data/games";
import { notFound, redirect } from "next/navigation";
import Link from "next/link";

export default function GamePage({
  params: { locale, slug },
}: {
  params: { locale: string; slug: string };
}) {
  const game = games.find((g) => g.slug === slug);
  if (!game) {
    notFound();
  }

  const title = locale === "zh" ? game.titleZh : game.title;
  const desc = locale === "zh" ? game.descriptionZh : game.description;
  const model = locale === "zh" ? game.aiModelZh : game.aiModel;

  return (
    <div className="min-h-screen pt-24 pb-16 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
      {/* Breadcrumb */}
      <div className="flex items-center gap-2 text-sm text-dark-500 mb-6">
        <Link href={`/${locale}`} className="hover:text-dark-300 transition-colors">
          {locale === "zh" ? "首页" : "Home"}
        </Link>
        <span>/</span>
        <Link href={`/${locale}#games`} className="hover:text-dark-300 transition-colors">
          {locale === "zh" ? "游戏" : "Games"}
        </Link>
        <span>/</span>
        <span className="text-white">{title}</span>
      </div>

      {/* Game Header */}
      <div className="mb-8">
        <div className="flex flex-wrap items-center gap-3 mb-4">
          <span className="ai-badge px-3 py-1 rounded-full text-xs font-mono flex items-center gap-1.5">
            <span className="w-1.5 h-1.5 rounded-full bg-neon-400 animate-pulse" />
            {locale === "zh" ? "100% AI 生成" : "100% AI Generated"}
          </span>
          {game.featured && (
            <span className="px-3 py-1 rounded-full text-xs font-mono bg-neon-500/10 text-neon-400 border border-neon-500/20">
              {locale === "zh" ? "精选" : "FEATURED"}
            </span>
          )}
          <span className="px-3 py-1 rounded-full text-xs font-mono bg-dark-700 text-dark-400 capitalize">
            {game.category}
          </span>
        </div>

        <h1 className="text-3xl sm:text-4xl font-bold mb-3">{title}</h1>
        <p className="text-dark-400 text-lg max-w-2xl">{desc}</p>

        <div className="flex flex-wrap items-center gap-6 mt-6 text-sm text-dark-400">
          <span className="flex items-center gap-1.5">
            ⭐ <span className="text-white font-semibold">{game.rating}</span>
          </span>
          <span>{game.plays.toLocaleString()} plays</span>
          <span className="flex items-center gap-1.5">
            <span className="w-2 h-2 rounded-full bg-neon-400" />
            {model}
          </span>
        </div>

        <div className="flex flex-wrap gap-2 mt-4">
          {game.tags.map((tag) => (
            <span
              key={tag}
              className="px-3 py-1 rounded-lg bg-dark-800 text-dark-400 text-xs font-mono border border-dark-700"
            >
              {tag}
            </span>
          ))}
        </div>
      </div>

      {/* Game Frame */}
      <div className="rounded-2xl overflow-hidden border border-dark-700 shadow-2xl shadow-neon-500/5 mb-12">
        <div className="bg-dark-900 px-4 py-3 flex items-center justify-between border-b border-dark-700">
          <div className="flex items-center gap-2">
            <div className="flex gap-1.5">
              <span className="w-3 h-3 rounded-full bg-red-500/80" />
              <span className="w-3 h-3 rounded-full bg-yellow-500/80" />
              <span className="w-3 h-3 rounded-full bg-neon-500/80" />
            </div>
            <span className="text-xs text-dark-500 ml-3 font-mono">
              {title.toLowerCase().replace(/\s+/g, "-")} — k399game
            </span>
          </div>
          <span className="text-[10px] text-neon-400/60 font-mono uppercase">
            AI GENERATED GAME
          </span>
        </div>
        <iframe
          src={game.gameUrl}
          className="w-full game-container bg-dark-950"
          title={title}
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          sandbox="allow-scripts allow-same-origin"
        />
      </div>

      {/* About AI Generation */}
      <div className="glass rounded-2xl p-8 max-w-2xl">
        <h3 className="text-lg font-bold mb-3">
          {locale === "zh" ? "关于 AI 生成" : "About AI Generation"}
        </h3>
        <p className="text-dark-400 text-sm leading-relaxed">
          {locale === "zh"
            ? `"${title}" 由 ${model} 完全生成。游戏的全部代码、视觉设计和游戏逻辑均由 AI 模型完成，没有任何人类代码编写参与。这展示了当前 AI 技术在互动娱乐领域的潜力和创造力。`
            : `"${title}" was entirely generated by ${model}. All game code, visual design, and gameplay logic were produced by the AI model with zero human coding intervention. This showcases the current potential and creativity of AI in interactive entertainment.`}
        </p>
      </div>

      {/* Back */}
      <div className="mt-12">
        <Link
          href={`/${locale}#games`}
          className="inline-flex items-center gap-2 text-dark-400 hover:text-white transition-colors text-sm"
        >
          <svg
            className="w-4 h-4"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth={2}
              d="M19 12H5m0 0l7 7m-7-7l7-7"
            />
          </svg>
          {locale === "zh" ? "返回游戏列表" : "Back to Games"}
        </Link>
      </div>
    </div>
  );
}
